language: r
sudo: false
cache: packages
matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.3
r_packages:
- covr
after_failure:
  email: 
    recipients:
     - thosjleeper@gmail.com
    on_success: change
    on_failure: change
after_success:
- Rscript -e 'library(covr);codecov()'
