# Sample .travis.yml for R projects.
#
# See README.md for instructions.

language: c
# To build on OSX, switch the previous line to
# language: objective-c
script: ./travis-tool.sh run_tests
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package assertthat
notifications:
  email:
    on_success: change
    on_failure: change
# Configuration options below this line are suggested options.
#
# One can also only dump logs on failure by using `after_failure`
# instead of `after_script`.
after_script:
  - ./travis-tool.sh dump_logs
#
# One can also restrict the branches to test, see
#   http://about.travis-ci.org/docs/user/build-configuration/#Specify-branches-to-build
# This example tests all branches except those with suffix -expt ("experimental").
# Note that in general it is advisable to test (almost) all branches in order to
# automatically test pending pull requests.
branches:
  only:
    - master
#
# Options used for building or testing your R package can be
# controlled by uncommenting one or both of the following; the values
# here are the defaults:
# env:
#   global:
#     - R_BUILD_ARGS="--no-build-vignettes"
#     - R_CHECK_ARGS="--no-manual --as-cran"
# See the travis docs for more information:
#   http://about.travis-ci.org/docs/user/build-configuration/#The-Build-Matrix
